bugtracker/Models/EditComment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace bugtracker.Models
{
    public class EditComment
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public DateTime Created { get; set; }
        public DateTime? Updated { get; set; }
    }
}

bugtracker/Models/TicketType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace bugtracker.Models
{
    public class TicketType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}

bugtracker/Models/Tickets.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace bugtracker.Models
{
    public class Tickets
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public DateTimeOffset Created { get; set; }
        public DateTimeOffset? Updated { get; set; }

        public int TicketTypeId { get; set; }
        public virtual TicketType TicketType { get; set; }

        public int TicketPriorityId { get; set; }
        public virtual TicketPriority TicketPriority { get; set; }

        public string CreatorId { get; set; }
        public virtual ApplicationUser Creator { get; set; }

        public int TicketStatusId { get; set; }
        public virtual TicketStatus TicketStatus { get; set; }

        public string AssigneeId { get; set; }
        public virtual ApplicationUser Assignee { get; set; }

        public int ProjectId { get; set; }
        public virtual Project Project { get; set; }

        public virtual ICollection<TicketAttachment> Attachments { get; set; }
        public virtual ICollection<TicketComment> Comments { get; set; }
        public virtual ICollection<TicketHistory> Histories { get; set; }

        public Tickets()
        {
            this.Created = DateTime.Now;
            Attachments = new HashSet<TicketAttachment>();
            Comments = new HashSet<TicketComment>();
            Histories = new HashSet<TicketHistory>();
        }
    }
}

bugtracker/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using bugtracker.Helpers;
using bugtracker.Models;
using Microsoft.AspNet.Identity;

namespace bugtracker.Controllers
{
    [Authorize]

    public class TicketsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Tickets
        public ActionResult Index()
        {
            var tickets = db.Tickets.
                Include(t => t.Assignee).
                Include(t => t.Creator).
                Include(t => t.Project).
                Include(t => t.TicketPriority).
                Include(t => t.TicketStatus).
                Include(t => t.TicketType);
            return View(tickets.ToList());
        }


        public ActionResult AssignTicketToDeveloper(int ticketId)
        {
            var model = new AssignTicketsViewModel();
            var ticket = db.Tickets.FirstOrDefault(p => p.Id == ticketId);
            var userRoleHelper = new UserRoleHelper();
            var users = userRoleHelper.UsersInRole("Developer");
            model.Id = ticketId;
            model.ListofDevelopers = new SelectList(users, "Id", "Name");
            return View(model);
        }

        [HttpPost]
        public ActionResult AssignTicketToDeveloper(AssignTicketsViewModel model)
        {
            var ticket = db.Tickets.FirstOrDefault(p => p.Id == model.Id);
            ticket.AssigneeId = model.SelectedDeveloperId;
            var user = db.Users.FirstOrDefault(p => p.Id == model.SelectedDeveloperId);
            ticket.Assignee = user;
            if (ticket.AssigneeId != null)
            {
                var personalEmailService = new PersonalEmailService();
                var mailMessage = new MailMessage(
                WebConfigurationManager.AppSettings["emailto"], ticket.Assignee.Email);
                mailMessage.Subject = "New Ticket";
                mailMessage.Body = "Boom! You have been assigned a new ticket";
                mailMessage.IsBodyHtml = true;
                personalEmailService.Send(mailMessage);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SubmitterTickets()
        {
            var userId = User.Identity.GetUserId();
            var ticketsSubmitter = db.Tickets.Where(p => p.CreatorId == userId).Include(t => t.Assignee).Include(t => t.Creator).Include(t => t.Project).Include(t => t.TicketPriority).Include(t => t.TicketStatus).Include(t => t.TicketType);
            return View("Index", ticketsSubmitter.ToList());
        }

        public ActionResult DeveloperTickets()
        {
            var userId = User.Identity.GetUserId();
            var ticketsDeveloper = db.Tickets.Where(ticket => ticket.AssigneeId == userId).Include(t => t.Assignee).Include(t => t.Creator).Include(t => t.Project).Include(t => t.TicketPriority).Include(t => t.TicketStatus).Include(t => t.TicketType);
            return View("Index", ticketsDeveloper.ToList());
        }

        public ActionResult TicketsForMyProjects()
        {
            string userId = User.Identity.GetUserId();
            var developerproject = db.Users.Where(p => p.Id == userId).FirstOrDefault();
            var projectsIds = developerproject.Projects.Select(p => p.Id).ToList();
            var Ticket = db.Tickets.Where(p => projectsIds.Contains(p.ProjectId)).ToList();
            return View("Index", Ticket);
        }

        // GET: Tickets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tickets tickets = db.Tickets.Find(id);
            if (tickets == null)
            {
                return HttpNotFound();
            }

            return View(tickets);
        }

        // GET: Tickets/Create
        [Authorize(Roles = "Submitter")]
        public ActionResult Create()
        {

            var userId = User.Identity.GetUserId();

            var projects = db.Projects
                .Where(p => p.Users.Any(m => m.Id == userId))
                .Select(p => new { p.Name, p.Id }).ToList();

            ViewBag.CreatorId = new SelectList(db.Users, "Id", "Name");
            ViewBag.ProjectId = new SelectList(projects, "Id", "Name");
            ViewBag.TicketPriorityId = new SelectList(db.TicketPriorities, "Id", "Name");
            ViewBag.TicketStatusId = new SelectList(db.TicketStatuses, "Id", "Name");
            ViewBag.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Submitter")]
        public ActionResult Create([Bind(Include = "Id,Name,Description,Updated,TicketTypeId,TicketPriorityId,AssigneeId,ProjectId")] Tickets tickets)
        {
            if (ModelState.IsValid)
            {
                tickets.CreatorId = User.Identity.GetUserId();
                tickets.TicketStatusId = 1;
                db.Tickets.Add(tickets);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CreatorId = new SelectList(db.Users, "Id", "Name", tickets.CreatorId);
            ViewBag.TicketPriorityId = new SelectList(db.TicketPriorities, "Id", "Name", tickets.TicketPriorityId);
            ViewBag.TicketStatusId = new SelectList(db.TicketStatuses, "Id", "Name", tickets.TicketStatusId);
            ViewBag.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name", tickets.TicketTypeId);
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name", tickets.ProjectId);
            return View(tickets);
        }

        // GET: Tickets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tickets tickets = db.Tickets.Find(id);
            if (tickets == null)
            {
                return HttpNotFound();
            }
            var userId = User.Identity.GetUserId();

            var projects = db.Projects
                .Where(p => p.Users.Any(m => m.Id == userId))
                .Select(p => new { p.Name, p.Id }).ToList();

            ViewBag.AssigneeId = new SelectList(db.Users, "Id", "DisplayName", tickets.AssigneeId);
            ViewBag.CreatorId = new SelectList(db.Users, "Id", "DisplayName", tickets.CreatorId);
            ViewBag.ProjectId = new SelectList(projects, "Id", "Name", tickets.ProjectId);
            ViewBag.TicketPriorityId = new SelectList(db.TicketPriorities, "Id", "Name", tickets.TicketPriorityId);
            ViewBag.TicketStatusId = new SelectList(db.TicketStatuses, "Id", "Name", tickets.TicketStatusId);
            ViewBag.TicketTypeId = new SelectList(db.TicketTypes, "Id", "Name", tickets.TicketTypeId);
            return View(tickets);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,TicketTypeId,TicketPriorityId,TicketStatusId,AssigneeId,ProjectId")] Tickets tickets)
        {
            if (ModelState.IsValid)
            {
                var datechanged = DateTimeOffset.Now;
                var changes = new List<TicketHistory>();

                var ticket = db.Tickets.FirstOrDefault(p => p.Id == tickets.Id);
                ticket.Name = tickets.Name;
                ticket.ProjectId = tickets.ProjectId;
                ticket.Description = tickets.Description;
                ticket.Updated = DateTime.Now;
                if (User.IsInRole("Admin") || User.IsInRole("Project Manager"))
                {
                    ticket.TicketStatusId = tickets.TicketStatusId;
                }
                ticket.TicketPriorityId = tickets.TicketPriorityId;
                ticket.TicketTypeId = tickets.TicketTypeId;

                var originalValues = db.Entry(ticket).OriginalValues;
                var CurrentValues = db.Entry(ticket).CurrentValues;

                foreach (var property in originalValues.PropertyNames)
                {
                    var originalValue = originalValues[property]?.ToString();
                    var currentValue = CurrentValues[property]?.ToString();

                    if (originalValue != currentValue)
                    {
                        var history = new TicketHistory();
                        history.Changed = datechanged;
                        history.NewValue = GetValueFromKey(property, currentValue);
                        history.OldValue = GetValueFromKey(property, originalValue);
                        history.Property = property;
                        history.TicketId = ticket.Id;
                        history.UserId = User.Identity.GetUserId();
                        changes.Add(history);


                    }
                }
                db.TicketHistories.AddRange(changes);
                if (tickets.AssigneeId != null)
                {
                    var personalEmailService = new PersonalEmailService();
                    var mailMessage = new MailMessage(
                    WebConfigurationManager.AppSettings["emailto"], tickets.Assignee.Email);

bugtracker/Views/Tickets/AssignTicketToDeveloper.cshtml
@model bugtracker.Models.AssignTicketsViewModel
@{
    ViewBag.Title = "AssignTicket";
}
<div class="left-content">
    <h2>Assign Tickets</h2>

    <section class="content">
        @using (Html.BeginForm())
        {<div class="form-group">
                @Html.HiddenFor(p => p.Id)
                @Html.DropDownListFor(p => p.SelectedDeveloperId, Model.ListofDevelopers, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ListofDevelopers, "", new { @class = "text-danger" })
                <input type="submit" value="Submit!" />
            </div>
        }
    </section>
</div>  

bugtracker/Views/Tickets/Create.cshtml
@model bugtracker.Models.Tickets

@{
    ViewBag.Title = "Create";
}
<div class="left-content">
<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Tickets</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    
    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProjectId, "ProjectId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ProjectId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TicketTypeId, "TicketTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TicketTypeId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TicketTypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TicketPriorityId, "TicketPriorityId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TicketPriorityId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TicketPriorityId, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
    </div>

bugtracker/Views/Tickets/Delete.cshtml
@model bugtracker.Models.Tickets

@{
    ViewBag.Title = "Delete";
}
<div class="left-content">

    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Tickets</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Assignee.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Assignee.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Creator.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Creator.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Project.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Project.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TicketPriority.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TicketPriority.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TicketStatus.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TicketStatus.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TicketType.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TicketType.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Created)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Created)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Updated)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Updated)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

bugtracker/Views/Tickets/Details.cshtml
@model bugtracker.Models.Tickets

@{
    ViewBag.Title = "Details";
}
<div class="left-content">
    <h2>Details</h2>

    <div>
        <h4>Tickets</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Assignee
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Assignee.Name)
            </dd>
            <dt>
                Created By
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Creator.Name)
            </dd>
            <dt>
                Project
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Project.Name)
            </dd>
            <dt>
                Priority
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TicketPriority.Name)
            </dd>
            <dt>
                Status
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TicketStatus.Name)
            </dd>
            <dt>
                Type
            </dt>
            <dd>
                @Html.DisplayFor(model => model.TicketType.Name)
            </dd>
            <dt>
                Name
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Created)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Created)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Updated)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Updated)
            </dd>

        </dl>


    </div>
    <h3> Comment on this Ticket</h3>
    <div>
        @using (Html.BeginForm("CreateComment", "Tickets", new { id = Model.Id }, FormMethod.Post))
        {
            <div class="row">
                <div class="col-md-6">
                    <input type="hidden" name="slug" value="@Model.Comments" />
                    <textarea name="Body"></textarea>
                    @if (ViewBag.ErrorMessage != null)
                    {
                        <span>@ViewBag.ErrorMessage</span>
                    }
                </div>
                <input type="submit" value="submit" />
            </div>
        }
    </div>
    <div>
        @foreach (var comment in Model.Comments)
        {
            <hr />
            <span style="font-size: 14px;">Creator: @comment.User.Name</span>
            <p style="text-align: left;">

                @comment.Comment

                <span style="font-size: 10px; text-align: right">

                    <span>Created: @comment.Created</span>

                    <span>Updated: @comment.Updated</span>



                </span>
            </p>


            <span style="font-size: 14px;"> @Html.ActionLink("Delete", "DeleteComment", new { id = comment.Id }) </span>

            <span style="font-size: 14px;"> @Html.ActionLink("Edit", "EditComment", new { id = comment.Id })</span>


        }

    </div>
    <hr/>

    <h3> Attachments </h3>
    <div>
        @using (Html.BeginForm("CreateAttachment", "Tickets", new { ticketId = Model.Id }, FormMethod.Post, new { enctype = "Multipart/form-data" }))
        {
            <div class="row">
                @Html.AntiForgeryToken()
                <div class="col-md-6">
                    <input name="image" type="file" class="form-control" id="fileUpload" />
                    @if (ViewBag.ErrorMessage != null)
                    {
                        <span>@ViewBag.ErrorMessage</span>
                    }
                </div>
                <div class="col-md-6">
                    <input type="submit" value="submit" />
                </div>
            </div>
        }
    </div>
    <div>
        @foreach (var attachment in Model.Attachments)
        {
            <hr />
            @attachment.User.Name
            <p style="text-align: left; margin-left: 70px">
                <a href="@attachment.FilePath">@attachment.FilePath </a>
                <span style="font-size: 10px; text-align: right">
                    @attachment.Created.ToString("mm/dd/yyyy hh:mm")
                </span>
            </p>
          <span style="font-size: 14px;"> @Html.ActionLink("Delete", "DeleteAttachment", new { id = attachment.Id }) </span>

        }
    </div>

    <hr />

    <h3> History </h3>
    <div>
        <table id="wer" class="table">
            <thead>
                <tr>
                    <th>
                        Property Changed
                    </th>
                    <th>
                        Old Value
                    </th>
                    <th>
                        New Value
                    </th>
                    <th>
                        Changed
                    </th>
                    <th>
                        Modifier
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Histories)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Property)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OldValue)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NewValue)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Changed)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.User.Name)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

bugtracker/Views/Tickets/Edit.cshtml
@model bugtracker.Models.Tickets

@{
    ViewBag.Title = "Edit";
}
<div class="left-content">
    <h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tickets</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.TicketPriorityId, "TicketPriorityId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TicketPriorityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TicketPriorityId, "", new { @class = "text-danger" })
            </div>
        </div>


        @if (User.IsInRole("Admin") || User.IsInRole("ProjectManager"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.TicketStatusId, "TicketStatusId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("TicketStatusId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TicketStatusId, "", new { @class = "text-danger" })
                </div>
            </div>

        }
        <div class="form-group">
            @Html.LabelFor(model => model.TicketTypeId, "TicketTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TicketTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TicketTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Project, "Project", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProjectId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

bugtracker/Views/Tickets/EditComment.cshtml
@model bugtracker.Models.TicketComment

@{
    ViewBag.Title = "EditComment";
}

<h2>EditComment</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TicketComment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>