bugtracker/Models/ManageRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace bugtracker.Models
{
    public class ManageRoleViewModel
    {
        public List<RoleViewModel> UserRoles { get; set; }
        public List<RoleViewModel> AllRoles { get; set; }

        public ManageRoleViewModel()
        {
            UserRoles = new List<RoleViewModel>();
            AllRoles = new List<RoleViewModel>();
        }
    }

    public class RoleViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
    }
}

bugtracker/Models/UserRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace bugtracker.Models
{
    public class UserRoleViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public List<string> UserRoles { get; set; }
    }
}

bugtracker/Controllers/UserRoleController.cs
using bugtracker.Helpers;
using bugtracker.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bugtracker.Controllers
{
    [Authorize]
    public class UserRoleController : Controller
    {
        private ApplicationDbContext Context;
        private UserManager<ApplicationUser> UserManager;

        public UserRoleController()
        {
            Context = new ApplicationDbContext();
            UserManager =
     new UserManager<ApplicationUser>(
             new UserStore<ApplicationUser>(Context));

        }
        
        public ActionResult Index()
        {
            var model = (from user in Context.Users
                         select new UserRoleViewModel
                         {
                             Email = user.Email,
                             Id = user.Id,
                             Name = user.Name,
                             UserRoles = (from userRoles in user.Roles
                                          join role in Context.Roles on userRoles.RoleId equals role.Id
                                          select role.Name).ToList()
                         }).ToList();

            return View(model);
        }

        [HttpGet]
        public ActionResult ManageRoles(string id)
        {
            var model = new ManageRoleViewModel();

            var user = Context.Users.FirstOrDefault(p => p.Id == id);

            var allRolesViewModel = Context.Roles.Select(p => new RoleViewModel
            {
                Id = p.Id,
                Name = p.Name
            }).ToList();

            var userRoleViewModel = (from userRoles in user.Roles
                                     join role in Context.Roles on userRoles.RoleId equals role.Id
                                     select new RoleViewModel
                                     {
                                         Id = role.Id,
                                         Name = role.Name
                                     }).ToList();

            model.AllRoles = allRolesViewModel;
            model.UserRoles = userRoleViewModel;

            return View(model);
        }

        [HttpPost]
        public ActionResult ManageRoles(string id, List<string> userRoleIds)
        {
            var user = Context.Users.FirstOrDefault(p => p.Id == id);

            var userRoles = user.Roles.ToList();

            foreach (var userRole in userRoles)
            {
                var role = Context.Roles.First(p => p.Id == userRole.RoleId).Name;
                UserManager.RemoveFromRole(user.Id, role);
            }

            foreach (var userRoleId in userRoleIds)
            {
                var role = Context.Roles.First(p => p.Id == userRoleId).Name;
                UserManager.AddToRole(user.Id, role);
            }

            return RedirectToAction(nameof(UserRoleController.Index));
        }
    }
}

bugtracker/Views/UserRole/Index.cshtml
@model List<bugtracker.Models.UserRoleViewModel>


@{
    ViewBag.Title = "Index";
}
@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#mytable').DataTable();
        });</script>
}
    <div class="left-content">

        <h2>Users</h2>

        <table id="mytable" class="grid-table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Roles</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in Model)
                {
                    <tr>
                        <td>@user.Name</td>
                        <td>@user.Email</td>
                        <td>@string.Join(",", user.UserRoles)</td>
                        <td><a href="@Url.Action("ManageRoles", "UserRole", new { id = user.Id })">Change roles</a></td>
                    </tr>
                }
            </tbody>
        </table>
        </div>

bugtracker/Views/UserRole/ManageRoles.cshtml
@model bugtracker.Models.ManageRoleViewModel

@{
    ViewBag.Title = "ChangeRole";
}
<div class="left-content">

    <h2>ChangeRole</h2>
    <form method="post">
        @foreach (var role in Model.AllRoles)
        {
            <input type="checkbox"
                   value="@role.Id"
                   name="userRoleIds"
                   @(Model.UserRoles.Any(p => p.Id == role.Id) ? "checked" : "") />
            @role.Name
        }
        <input type="submit" value="Submit" class="btn btn-primary" />
    </form>
</div>